//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RpgBooks.Libraries.System.Validation.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error!.
        /// </summary>
        internal static string DefaultValidationExceptionMessage {
            get {
                return ResourceManager.GetString("DefaultValidationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} cannot be empty..
        /// </summary>
        internal static string EmptyStringErrorMessageFormat {
            get {
                return ResourceManager.GetString("EmptyStringErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        internal static string ForGreaterThanOrEqualToErrorMessageFormat {
            get {
                return ResourceManager.GetString("ForGreaterThanOrEqualToErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be non-negative..
        /// </summary>
        internal static string ForGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("ForGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be positive..
        /// </summary>
        internal static string ForGreaterThanZeroErrorMessageFormat {
            get {
                return ResourceManager.GetString("ForGreaterThanZeroErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain only digits..
        /// </summary>
        internal static string ForHasOnlyDigitsErrorMessageFormat {
            get {
                return ResourceManager.GetString("ForHasOnlyDigitsErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid URL..
        /// </summary>
        internal static string ForIsValidUrlErrorMessageFormat {
            get {
                return ResourceManager.GetString("ForIsValidUrlErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be non-positive..
        /// </summary>
        internal static string ForLessThanOrEqualToZeroErrorMessageFormat {
            get {
                return ResourceManager.GetString("ForLessThanOrEqualToZeroErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        internal static string GreaterThanErrorMessageFormat {
            get {
                return ResourceManager.GetString("GreaterThanErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        internal static string LessThanErrorMessageFormat {
            get {
                return ResourceManager.GetString("LessThanErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}..
        /// </summary>
        internal static string LessThanOrEqualToErrorMessageFormat {
            get {
                return ResourceManager.GetString("LessThanOrEqualToErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be negative..
        /// </summary>
        internal static string LessThanZeroErrorMessageFormat {
            get {
                return ResourceManager.GetString("LessThanZeroErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have maximum length of {1} characters..
        /// </summary>
        internal static string MaxLengthErrorMessageFormat {
            get {
                return ResourceManager.GetString("MaxLengthErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        internal static string MinLengthErrorMessageFormat {
            get {
                return ResourceManager.GetString("MinLengthErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should have value!.
        /// </summary>
        internal static string NullValueErrorMessageFormat {
            get {
                return ResourceManager.GetString("NullValueErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value has invalid format!.
        /// </summary>
        internal static string WrongFormatErrorMessageFormat {
            get {
                return ResourceManager.GetString("WrongFormatErrorMessageFormat", resourceCulture);
            }
        }
    }
}
