name: Build and Test Debug

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Test Debug
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Specify the desired .NET version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug

    - name: Run Tests
      run: dotnet test --configuration Debug --no-build
